services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PYTHONPATH: /workspace
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/workspace
    command: python /workspace/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/workspace/frontend
    ports:
      - "5173:5173"
    depends_on:
      - app
    command: bash -c "cd /workspace/frontend && npm install && npm run dev"
    stdin_open: true
    tty: true
    working_dir: /workspace/frontend
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - app
    stdin_open: true
    tty: true

volumes:
  postgres_data:
