# Generated by Django 4.2.13 on 2025-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='arts/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='art',
            field=models.ImageField(upload_to='arts/'),
        ),
    ]
