# Generated by Django 4.2.13 on 2024-08-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='home',
            name='twitter',
        ),
    ]
