# Generated by Django 4.2.13 on 2024-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_home_instagram_home_twitter_alter_home_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='art_home'),
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ImageField(upload_to='art_gallery')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('like_sum', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ManyToManyField(to='gallery.gallery')),
            ],
        ),
    ]
