version: '3'

services:
    app:
        image: python:3.11
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        environment:
            PYTHONPATH: /workspace
        volumes:
            - ..:/workspace
        command: sleep infinity